name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Capacitor
      run: npm install -g @capacitor/cli
      
    - name: Add Android platform
      run: npx cap add android
      
    - name: Sync project
      run: npx cap sync android
      
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0
        platform: android-34
      
    - name: Accept Android licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
      
    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
      
    - name: Build APK Debug
      run: |
        cd android
        chmod +x gradlew
        export ANDROID_HOME=$ANDROID_HOME
        export JAVA_HOME=$JAVA_HOME
        ./gradlew assembleDebug --stacktrace --info
      
    - name: List build outputs
      run: |
        find android -name "*.apk" -type f
        ls -la android/app/build/outputs/apk/debug/ || echo "Debug folder not found"
        ls -la android/app/build/outputs/apk/release/ || echo "Release folder not found"
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: warn
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: warn 




